# GRIEVANCE SEGRIGATION 

Necessary Imports

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_colwidth',None)   
import collections
from collections import Counter

In [3]:
dataset = pd.read_excel("FINAL.xlsx")

Top Five Dataset

In [4]:
dataset.head()

गुनासो वर्ग  \
0  लागु पदार्थ सम्बन्धी    
1  लागु पदार्थ सम्बन्धी    
2  लागु पदार्थ सम्बन्धी    
3  लागु पदार्थ सम्बन्धी    
4  लागु पदार्थ सम्बन्धी    

                                                                                                                                                                                                            गुनासो  
0                                          धनुषा जील्ला वडा न‍ २३  जिरो माइल प्रहरी चौकी नजिक रहेका ८ वटा पसलहरुमा घरेलु मदीरा बक्री भैरहेको छ । उत कार्यमा  जिरो माइल प्रहरी चौकिका इन्चार्ज चन्दन शीह को मीलोमतो  
1                                                                                                                                                        भारतिय नागरिकले लागु पदार्थ सेवन गरि जथाभावि बोल्ने गरेको  
2  अन्तर्राष्ट्रिय सिमाना नजिकै हुने मदिरा को व्यापार  ले भारतीय नागरिक हरु को बाक्लो आवत जावत हुने गर्दछ र नशा मा मात्तिएर उनिहरु दैनिक जसो  स्थानिय को घर अगाडि जथाभावी बोल्ने झगडा गर्ने जस्ता घटना नौला होइनन्  
3                                                                         तामाङ्ग गुम्बा नजिक  राति राति  मादकपदार्थको बिक्रि वितरण गर्ने र मादकपदार्थ  खाई होहल्ला गरेको कारणले  स्थानिय बासिन्दालाई समस्या परेको  
4                                                      देशका विभिन्न ठाउहरूमा सुर्तिजन्य तथा मदिराजन्य पदार्थको खुलमखुल्ला विक्रि वितरण भैरहेकोले यसको नियमन गर्नुपर्ने देखियो भन्ने व्यहोराको गुनासो प्राप्त भएको

Naming of Class and Data

In [4]:
X1=dataset['गुनासो']
Y1=list(dataset['गुनासो वर्ग'])

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10335 entries, 0 to 10334
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   गुनासो वर्ग  10335 non-null  object
 1   गुनासो       10335 non-null  object
dtypes: object(2)
memory usage: 161.6+ KB


### Remove stopwords

import nltk
from nltk.corpus import stopwords

stopWords = set(nltk.corpus.stopwords.words('nepali'))

stopWords=set(stopwords.words('nepali'))
X_data=[]
for i in X:
    गुनासो=' '.join([word for word in i.split() if word not in stopWords])
    X_data.append(गुनासो.strip())

Stopwords = set(nltk.corpus.stopwords.words('english'))

Stopwords=set(stopwords.words('english'))
X_data=[]
for i in X:
    गुनासो=' '.join([word for word in i.split() if word not in Stopwords])
    X_data.append(गुनासो.strip())

#removing all unnecessary expression
import re
def processText(गुनासो):
    गुनासो = गुनासो.lower()
    गुनासो = re.sub(r'((www.[^s]+)|(https?://[^s]+))',r'',गुनासो)
    गुनासो = re.sub(r'[s]+', r'',गुनासो)
    गुनासो = re.sub(r'#([^s]+)', r'', गुनासो)
    गुनासो = re.sub(r'[.!:?"\।|,]', r'', गुनासो)
    गुनासो = re.sub(r'[\u0966-\u096F]+',r'',गुनासो)
    गुनासो = re.sub(r'[\([{})\]]',r'',गुनासो)
    गुनासो = re.sub(r'[a-zA-Z0-9\+\-\'\"\%\&\$]',r'',गुनासो)
    गुनासो = गुनासो.strip()
    
    return गुनासो

for i in range(len(dataset)):
    dataset['गुनासो'][i] = processText(dataset['गुनासो'][i])

dataset.head()

import collections
from collections import Counter

corpus_list =[]
for i,t in enumerate(X_data):
    wordArr = X_data[i].split(" ")
    for j, p in enumerate(wordArr):
        corpus_list.append(wordArr[j])
counter=collections.Counter(corpus_list)

least_common= [word for word, word_count in Counter(corpus_list).most_common()[:-50:-1]]
for i,t in enumerate(X_data):
    word = X_data[i].split(" ")
    X_data[i] = " ".join(ele for ele in word if ele not in least_common)

count = 0;
for i in X:
    X_data[count] = processText(X_data[count])
    count= count +1

Nepali Stopwords

In [6]:
stopwords_nepali = ['यो','म','यी','त्यो','ती','प्रति','हरेक','प्रतेक','माननीय','अलिकति','थोरै','सबै','केहि','एक','दुई','तिन','प्रथम','रही','आज','द्रितीय','तृतीय','को','सब','कुन','जी','श्री','वैसा','कति','जो', 'जसरी', 'जुन', 'र', 'तथा', 'तर', 'आदि', 'किन्तु', 'इत्यादि', 'परन्तु', 'ले', 'बाट', 'लाई', 'ले', 'द्वारा', 'वारि', 'पारि', 'अघाडी', 'कुमारी', 'चित्रकार', 'राम', 'उन', 'उनका', 'उनकी', 'पर्दिप', 'उनको', 'उस', 'एक', 'एवं', 'एस', 'कई', 'कहा', 'का', 'काफ़ी', 'कि','की', 'कुल', 'के', 'को', 'कोई', 'घर', 'जब', 'जहाँ', 'जा', 'जो', 'तब','तिस', 'थिए','हरि','थे', 'होला','द्वारा', 'न','ने', 'पर','पूरा','पे', 'यदि', 'यहाँ', 'यही', 'या', 'वर्ग','संग','हो','जेसे','दवारा','यहां','जे', 'यहि','मोबि','अदि','छ','हेरीच्छ','जहां']
#to_be_removed = stopwords_nepali 

for i in range(len(dataset)):
    dataset['गुनासो'][i]=[ele for ele in dataset['गुनासो'][i] if ele not in (to_be_removed)]

dataset.head()

for i,t in enumerate(X_data):
    word = X_data[i].split(" ")
    X_data[i] = " ".join(ele for ele in word if ele not in to_be_removed)

dataset.head()

### Vectorizer

X1=dataset['गुनासो']
Y1=list(dataset['गुनासो वर्ग'])

In [7]:
from sklearn.model_selection import train_test_split

Train and Test dataset (70% training size and 30% testing size)

In [9]:
X_train,X_test,Y_train,Y_test=train_test_split(X1,Y1,test_size=0.30,random_state=0)

Term frequency count by TFIDF(Term Frequency Inverse Document Frequency) (Repeated word count for ML analysis)

In [10]:

from sklearn.feature_extraction.text import TfidfVectorizer

In [11]:
def tfidf_features(X_train, X_test):
    tfidf_vectorizer = TfidfVectorizer(stop_words=stopwords_nepali)
    X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
    X_test_tfidf = tfidf_vectorizer.transform(X_test)
    return X_train_tfidf,X_test_tfidf,tfidf_vectorizer.vocabulary_
X_train_tfidf,X_test_tfidf,vocabulary=tfidf_features(X_train,X_test)


C:\Users\Dell\AppData\Roaming\Python\Python310\site-packages\sklearn\feature_extraction\text.py:404: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['अघ', 'अद', 'अल', 'आद', 'इत', 'उनक', 'एव', 'कत', 'कह', 'जसर', 'जह', 'तथ', 'दव', 'नन', 'परन', 'यद', 'यह', 'रक', 'रत', 'रथम', 'रह', 'वर', 'हर'] not in stop_words.
  warnings.warn(


Sparse to Dense for Naive Bayes (Sparse matrix to dense matrix as sparse matrix contains zero values which is not read by Naive Bayes)

In [12]:
#Convert Sparse to Dense
X_train_Vectorized_Dense = X_train_tfidf.todense()
X_test_Vectorized_Dense = X_test_tfidf.todense()

### ML ALGO

In [13]:
from sklearn.svm import LinearSVC
from sklearn.ensemble import ExtraTreesClassifier,GradientBoostingClassifier,RandomForestClassifier,AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression,RidgeClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

Function for accuracy and F1 for Dense

In [16]:
def ClassificationAlgorithm_dense(func, **kwargs):

  def innerFunction():
    model = func(**kwargs)
    model.fit(X_train_Vectorized_Dense, Y_train)

    Y_pred = model.predict(X_test_Vectorized_Dense)
    
    print("Confusion Matrix : \n",confusion_matrix(Y_test,Y_pred),"\n")
    print("Accuracy Score : ",accuracy_score(Y_test,Y_pred))
    print("F1 Score : ",f1_score(Y_test,Y_pred,average='weighted'))

  return innerFunction()

Function for accuracy and F1 for Sparse

In [17]:
def ClassificationAlgorithm(func, **kwargs):

  def innerFunction():
    model = func(**kwargs)
    model.fit(X_train_tfidf,Y_train)
    
    Y_pred= model.predict(X_test_tfidf)
    
    print ("Confusion Matrix : \n", confusion_matrix(Y_test, Y_pred), "\n")
    print("Testing Accuracy is  :%s" %(model.score(X_test_tfidf, Y_test)))
    print ("F1 Score : " , f1_score(Y_test, Y_pred, average='weighted'))
    
  return innerFunction()

### SUPPORT VECTOR MACHINE (SVM)

In [18]:
from sklearn.svm import LinearSVC
ClassificationAlgorithm(LinearSVC)

Confusion Matrix : 
 [[143   1  27   4   1   2  24   6   6  29  10]
 [  4   0   7   1   1   0   1   1   0   2   1]
 [ 27   1 249  10   3   3  42   8   3  37  21]
 [  5   0  14 157   3   1  15   4   3  13   4]
 [  6   0   8   2  39   1   7   1   0  10   2]
 [  2   0   4   0   0  24   2   3   3   3   2]
 [ 16   0  31  12   0   1 716   2   4 108   7]
 [  9   1  24   8   2   3  14  86   2  19   8]
 [  9   0   5   5   0   2  22   3 131  15   4]
 [ 25   0  47  10   5   0 179   5  10 262  22]
 [ 15   0  35   5   2   1  11   5   5  35 140]] 

Testing Accuracy is  :0.6278619800064495
F1 Score :  0.6232087931773601


In [19]:
from sklearn.svm import SVC
ClassificationAlgorithm(SVC,kernel='rbf')

Confusion Matrix : 
 [[111   0  41   1   0   0  52   0   0  46   2]
 [  1   0   9   1   0   0   2   0   0   3   2]
 [ 10   0 247   4   0   1  72   2   2  56  10]
 [  1   0  10 137   0   0  29   1   3  37   1]
 [  4   0  10   2  23   0  18   1   0  18   0]
 [  1   0  12   1   0  12   3   1   0   9   4]
 [  5   0  21   7   0   0 776   0   1  84   3]
 [  7   0  35   2   0   0  37  65   1  27   2]
 [  4   0   4   5   0   1  53   2 107  18   2]
 [ 11   0  40   5   0   0 218   0   3 278  10]
 [  8   0  38   5   0   0  38   0   1  51 113]] 

Testing Accuracy is  :0.6027088036117382
F1 Score :  0.5926726933349344


In [20]:
from sklearn.svm import SVC
ClassificationAlgorithm(SVC,kernel='poly')

Confusion Matrix : 
 [[ 36   0  25   0   0   0 161   0   0  30   1]
 [  1   0   6   0   0   0   9   0   0   2   0]
 [  2   0 172   1   0   0 185   0   0  41   3]
 [  0   0   3  40   0   0 156   0   0  20   0]
 [  0   0   6   0   5   0  55   1   0   9   0]
 [  0   0   3   0   0   1  37   0   0   2   0]
 [  1   0   7   0   0   0 853   0   0  36   0]
 [  1   0  21   0   0   0 108  37   0   9   0]
 [  1   0   3   0   0   0 143   0  31  18   0]
 [  1   0  23   0   0   0 378   0   0 162   1]
 [  1   0  17   0   0   0 165   0   1  31  39]] 

Testing Accuracy is  :0.4437278297323444
F1 Score :  0.38899729336661915



### Naive Bayes

In [ ]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, ComplementNB

In [21]:
#Convert Sparse to Dense
X_train_Vectorized_Dense = X_train_tfidf.todense()
X_test_Vectorized_Dense = X_test_tfidf.todense()

Gaussian Naive Bayes'

In [22]:
from sklearn.naive_bayes import GaussianNB
ClassificationAlgorithm_dense(GaussianNB)

C:\Users\Dell\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
C:\Users\Dell\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


Confusion Matrix : 
 [[ 76  20  44  11   6   6  15  16  17  25  17]
 [  4   2   4   0   1   0   0   2   0   3   2]
 [ 39  20 183  14  12  13  22  21  17  36  27]
 [ 13  29  25  77   8  11   5  12  11  16  12]
 [  1   3  27   2  18   4   4   4   1   9   3]
 [  2   5   3   2   3  18   0   4   0   1   5]
 [ 93  73  58  52  10  22 314  18  85 144  28]
 [ 11   3  34   0   6   3   8  74   7  19  11]
 [  8  12  28   5   4   2  23   2  87  19   6]
 [ 52  54  75  30  11  18  74  31  41 134  45]
 [ 19  13  40  11   6   6   7  10  15  31  96]] 

Accuracy Score :  0.34795227346017416
F1 Score :  0.366232893403448


Bernoulli Naive Bayes'

In [ ]:
ClassificationAlgorithm_dense(BernoulliNB)

Multinomial Naive Bayes'

In [ ]:
ClassificationAlgorithm_dense(MultinomialNB)

Complement Naive Bayes'

In [ ]:
ClassificationAlgorithm_dense(ComplementNB)

### Multi lingual bert

In [23]:
from simpletransformers.classification import ClassificationModel

KeyboardInterrupt: 

In [22]:
print(set(Y_train))

{'अर्थ सबन्धी', 'शान्ति सुरक्षा सम्बन्धी', 'स्वास्थ्यसँग सम्बन्धी', 'सूचना तथा संचार सम्बन्धी'}


In [23]:
from sklearn import preprocessing
labeler = preprocessing.LabelEncoder()

df3 = pd.DataFrame(X_train)
df3['label'] = labeler.fit_transform(Y_train)
print(df3.head())

                                                                                                                                                                                                                                                                                                                                                                           गुनासो  \
610                                                                                                                                                                    बिज्ञापन निकालेर राजस्ब लिएको महीनौ बितीसकदा पनि firm summit na vyeko र राजस्ब लीएर अहीले सम्म कुनैपनि परीक्षा मिति निकालेको छैन ।\n राज्सब फ्रिता गरिपाउ या परिक्षा काे मिति पाउ भनि याे सानाे अनुराेध छ।   
1458  दुवै NTC र NCELL को नेटवर्क ले राम्रो काम गर्दैन। 2g network full देखाउँछ तर कल लाग्दैन । balance धरी चेक हुँदैन। 3g 4g network १-२ line signal आउछ तर call र DATA राम्रो चल्दैन ।। नेट चलाउनु फरक फरक ठाउँ खोज्दै की बाटोतिर की खेत तिर जानुपर्छ। MAIN 

In [40]:
model = ClassificationModel('bert', 'bert-base-multilingual-uncased', num_labels=4, use_cuda=False, args={
    'reprocess_input_data': True,
    'use_cached_eval_features': False,
    'overwrite_output_dir': True,
    'num_train_epochs': 3
})
model.train_model(df3)
print("trained model")

Some weights of the model checkpoint at bert-base-multilingual-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model 

  0%|          | 0/2173 [00:00<?, ?it/s]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The 

Epoch:   0%|          | 0/3 [00:00<?, ?it/s]

Running Epoch 0 of 3:   0%|          | 0/272 [00:00<?, ?it/s]

Running Epoch 1 of 3:   0%|          | 0/272 [00:00<?, ?it/s]

Running Epoch 2 of 3:   0%|          | 0/272 [00:00<?, ?it/s]

trained model


In [41]:
eval_frame = pd.DataFrame(X_test)
eval_frame['label'] = labeler.fit_transform(Y_test)
print(eval_frame.head())

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   गुनासो  \
1946                                                                                                                                                                                                                                       

In [42]:
print(len(eval_frame))

725


In [43]:
result, model_outputs, wrong_predictions = model.eval_model(eval_frame)
bads = {}
for pred in wrong_predictions:
    if pred.label in bads:
        bads[pred.label] += 1
    else:
        bads[pred.label] = 1
print("wrong predictions (by input I think?):")
print(bads)

/Users/badalgami/opt/anaconda3/lib/python3.9/site-packages/simpletransformers/classification/classification_model.py:1442: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  warnings.warn(


  0%|          | 0/725 [00:00<?, ?it/s]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


Running Evaluation:   0%|          | 0/91 [00:00<?, ?it/s]

wrong predictions (by input I think?):
{0: 107, 1: 64, 3: 50, 2: 81}


In [46]:
(1-(107+64+50+81)/725)*100

58.34482758620689