# GRIEVANCE SEGRIGATION 

In [44]:
import pandas as pd
import numpy as np
pd.set_option('display.max_colwidth',None)   
import collections
from collections import Counter

Read Dataset

In [45]:
dataset = pd.read_excel("4_label.xlsx")

Top 5 dataset (Visualization)

In [46]:
dataset.head()

गुनासो वर्ग  \
0  अर्थ सबन्धी   
1  अर्थ सबन्धी   
2  अर्थ सबन्धी   
3  अर्थ सबन्धी   
4  अर्थ सबन्धी   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      गुनासो  
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ओम शिव शक्ति बचत तथा ऋण सहकारी संस्थाले युवा स्वरोजगार कार्यक्रमबाट सहकारी मार्फत कार्यक्रम सञ्चालन गर्ने भनि करिब ३०-४० व्यक्तिको फायल तयार गरी करिव २ करोड रूपैया निकासी गरेतापनि सम्बन्धित व्यक्तिलाई रूपैया नदिएर यस सहकारी संस्थाको अध्यक्षले उक्त रकम आफूले जग्गा पलटिङको कार्यमा प्रयोग गरेका छन्। कार्यक्रमको अनुगमनको लागि नेपाल सरकारका कर्मचारी आएपनि उहाँहरू बिरगञ्जको कुनै होटलमा बसि फर्किनु भएको छ । यस बारे छानविन गरी कारवाही गरिपाउँ ।  
1  एनआइसी एसीया बैंक डिल्लिबजार शाखाले दिएको चेक बाउन्सको फेक रिपोर्टका आधारमा महानगरीय प्रहरी परिसर ललितपुरले दाङ तुलसीपुर–५ स्थायी ठेगाना भएकी ललितपुरको नखिपोट बस्ने शिक्षा पेशामा आवद्ध भएकी कान्ति गिरी र उनका पति रुपेश श्रेष्ठलाई सोही आधारमा ललितपुर प्रहरीले केही साता अघि पक्राउ गर्‍यो । १ साउनमा प्रहरीले धरौटीमा रिहा हुनसाथ पुनः गिरी दम्पत्तीलाई पक्राउ गरेको थियो । बैंकिङ कसुरका लागि बैंकले तीन पटक चेक बाउन्स गर्न तीन साता लगाउँछ तर डिल्लिबजार शाखाले पीडकको दबाबमा आएर तीन दिनमा नै तीन पटक बाउन्स गरिदियो । १७, १८ र १९ असारमा चेक बाउन्सको रिपोर्ट बनाएपछि पीडकले गिरी दम्पत्तीलाई प्रहरीसम्म पुराए । उक्त खाता १० असारमा नै बन्द गरिएको थियो । गिरीको एनआइसी एसीया बैंकको डिल्लिबजार शाखाको खाता नम्बर २९५६३५१८२१५२४००१ को चेक पीडक दम्पत्ती राजेश र प्रिती अवालेले धम्की दिएर काट्न लगाएको पीड

Naming for class and data

In [47]:
X=dataset['गुनासो']
Y=list(dataset['गुनासो वर्ग'])

In [48]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2898 entries, 0 to 2897
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   गुनासो वर्ग  2898 non-null   object
 1   गुनासो       2898 non-null   object
dtypes: object(2)
memory usage: 45.4+ KB


### Remove stopwords

In [49]:
import nltk
from nltk.corpus import stopwords

In [50]:
stopWords = set(nltk.corpus.stopwords.words('nepali'))

Stop word removal (Nepali)

In [51]:
stopWords=set(stopwords.words('nepali'))
X_data=[]
for i in X:
    गुनासो=' '.join([word for word in i.split() if word not in stopWords])
    X_data.append(गुनासो.strip())

Stopword removal (English)

In [52]:
Stopwords = set(nltk.corpus.stopwords.words('english'))

In [53]:
Stopwords=set(stopwords.words('english'))
X_data=[]
for i in X:
    गुनासो=' '.join([word for word in i.split() if word not in Stopwords])
    X_data.append(गुनासो.strip())

Stop word removal along with english words, numbers and special symbols from regular expressioon


In [54]:
#removing all unnecessary expression
import re
def processText(गुनासो):
    गुनासो = गुनासो.lower()
    गुनासो = re.sub(r'((www.[^s]+)|(https?://[^s]+))',r'',गुनासो)
    गुनासो = re.sub(r'[s]+', r'',गुनासो)
    गुनासो = re.sub(r'#([^s]+)', r'', गुनासो)
    गुनासो = re.sub(r'[.!:?"\।|,]', r'', गुनासो)
    गुनासो = re.sub(r'[\u0966-\u096F]+',r'',गुनासो)
    गुनासो = re.sub(r'[\([{})\]]',r'',गुनासो)
    गुनासो = re.sub(r'[a-zA-Z0-9\+\-\'\"\%\&\$]',r'',गुनासो)
    गुनासो = गुनासो.strip()
    
    return गुनासो

Processing after removal

In [55]:
for i in range(len(dataset)):
    dataset['गुनासो'][i] = processText(dataset['गुनासो'][i])

In [56]:
dataset.head()

गुनासो वर्ग  \
0  अर्थ सबन्धी   
1  अर्थ सबन्धी   
2  अर्थ सबन्धी   
3  अर्थ सबन्धी   
4  अर्थ सबन्धी   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 गुनासो  
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ओम शिव शक्ति बचत तथा ऋण सहकारी संस्थाले युवा स्वरोजगार कार्यक्रमबाट सहकारी मार्फत कार्यक्रम सञ्चालन गर्ने भनि करिब  व्यक्तिको फायल तयार गरी करिव  करोड रूपैया निकासी गरेतापनि सम्बन्धित व्यक्तिलाई रूपैया नदिएर यस सहकारी संस्थाको अध्यक्षले उक्त रकम आफूले जग्गा पलटिङको कार्यमा प्रयोग गरेका छन् कार्यक्रमको अनुगमनको लागि नेपाल सरकारका कर्मचारी आएपनि उहाँहरू बिरगञ्जको कुनै होटलमा बसि फर्किनु भएको छ  यस बारे छानविन गरी कारवाही गरिपाउँ  
1  एनआइसी एसीया बैंक डिल्लिबजार शाखाले दिएको चेक बाउन्सको फेक रिपोर्टका आधारमा महानगरीय प्रहरी परिसर ललितपुरले दाङ तुलसीपुर– स्थायी ठेगाना भएकी ललितपुरको नखिपोट बस्ने शिक्षा पेशामा आवद्ध भएकी कान्ति गिरी र उनका पति रुपेश श्रेष्ठलाई सोही आधारमा ललितपुर प्रहरीले केही साता अघि पक्राउ गर्‍यो   साउनमा प्रहरीले धरौटीमा रिहा हुनसाथ पुनः गिरी दम्पत्तीलाई पक्राउ गरेको थियो  बैंकिङ कसुरका लागि बैंकले तीन पटक चेक बाउन्स गर्न तीन साता लगाउँछ तर डिल्लिबजार शाखाले पीडकको दबाबमा आएर तीन दिनमा नै तीन पटक बाउन्स गरिदियो    र  असारमा चेक बाउन्सको रिपोर्ट बनाएपछि पीडकले गिरी दम्पत्तीलाई प्रहरीसम्म पुराए  उक्त खाता  असारमा नै बन्द गरिएको थियो  गिरीको एनआइसी एसीया बैंकको डिल्लिबजार शाखाको खाता नम्बर  को चेक पीडक दम्पत्ती राजेश र प्रिती अवालेले धम्की दिएर काट्न लगाएको पीडितले बताएका छन्  यस्तै धम्की दिएरै विभिन्न मितिका अन्य चेक पनि अवाले दम्पत्तीले काट्न लगाएको छ  ललितपुर परिसरमा यसअघिको छलफलका क्रममा पीडि

In [57]:
import collections
from collections import Counter

Counter used for word count 

In [58]:
corpus_list =[]
for i,t in enumerate(X_data):
    wordArr = X_data[i].split(" ")
    for j, p in enumerate(wordArr):
        corpus_list.append(wordArr[j])
counter=collections.Counter(corpus_list)

Removal of least common word

In [59]:
least_common= [word for word, word_count in Counter(corpus_list).most_common()[:-50:-1]]
for i,t in enumerate(X_data):
    word = X_data[i].split(" ")
    X_data[i] = " ".join(ele for ele in word if ele not in least_common)

In [60]:
count = 0;
for i in X:
    X_data[count] = processText(X_data[count])
    count= count +1

Nepali stopwords

In [61]:
stopwords_nepali = ['यो','म','यी','त्यो','ती','प्रति','हरेक','प्रतेक','माननीय','अलिकति','थोरै','सबै','केहि','एक','दुई','तिन','प्रथम','रही','आज','द्रितीय','तृतीय','को','सब','कुन','जी','श्री','वैसा','कति','जो', 'जसरी', 'जुन', 'र', 'तथा', 'तर', 'आदि', 'किन्तु', 'इत्यादि', 'परन्तु', 'ले', 'बाट', 'लाई', 'ले', 'द्वारा', 'वारि', 'पारि', 'अघाडी', 'कुमारी', 'चित्रकार', 'राम', 'उन', 'उनका', 'उनकी', 'पर्दिप', 'उनको', 'उस', 'एक', 'एवं', 'एस', 'कई', 'कहा', 'का', 'काफ़ी', 'कि','की', 'कुल', 'के', 'को', 'कोई', 'घर', 'जब', 'जहाँ', 'जा', 'जो', 'तब','तिस', 'थिए','हरि','थे', 'होला','द्वारा', 'न','ने', 'पर','पूरा','पे', 'यदि', 'यहाँ', 'यही', 'या', 'वर्ग','संग','हो','जेसे','दवारा','यहां','जे', 'यहि','मोबि','अदि','छ','हेरीच्छ','जहां','अक', 'अग', 'अझ', 'अन', 'अर', 'आजक', 'आत', 'आद', 'आफ', 'आय', 'ईक', 'उद', 'उनक', 'उनल', 'उह', 'एउट', 'एन', 'कत', 'कम', 'कस', 'कसर', 'कह', 'गत', 'गय', 'गर', 'चम', 'छन', 'जत', 'जबक', 'जस', 'जसक', 'जसब', 'जसम', 'जसल', 'जह', 'तत', 'तथ', 'तदन', 'तप', 'तवम', 'नज', 'नत', 'नभन', 'नय', 'पक', 'पछ', 'पन', 'पय', 'पर', 'पष', 'पह', 'बन', 'बर', 'भएक', 'भय', 'भव', 'मल', 'यत', 'यथ', 'यद', 'यप', 'यसक', 'यसपछ', 'यसब', 'यसर', 'यह', 'रण', 'रत', 'रमश', 'रह', 'लस', 'वर', 'सक', 'सट', 'सध', 'सपछ', 'सब', 'सम', 'सर', 'सह', 'हन', 'हर', 'हरण']
to_be_removed = stopwords_nepali 

for i in range(len(dataset)):
    dataset['गुनासो'][i]=[ele for ele in dataset['गुनासो'][i] if ele not in (to_be_removed)]

In [62]:
dataset.head()

गुनासो वर्ग  \
0  अर्थ सबन्धी   
1  अर्थ सबन्धी   
2  अर्थ सबन्धी   
3  अर्थ सबन्धी   
4  अर्थ सबन्धी   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 गुनासो  
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ओम शिव शक्ति बचत तथा ऋण सहकारी संस्थाले युवा स्वरोजगार कार्यक्रमबाट सहकारी मार्फत कार्यक्रम सञ्चालन गर्ने भनि करिब  व्यक्तिको फायल तयार गरी करिव  करोड रूपैया निकासी गरेतापनि सम्बन्धित व्यक्तिलाई रूपैया नदिएर यस सहकारी संस्थाको अध्यक्षले उक्त रकम आफूले जग्गा पलटिङको कार्यमा प्रयोग गरेका छन् कार्यक्रमको अनुगमनको लागि नेपाल सरकारका कर्मचारी आएपनि उहाँहरू बिरगञ्जको कुनै होटलमा बसि फर्किनु भएको छ  यस बारे छानविन गरी कारवाही गरिपाउँ  
1  एनआइसी एसीया बैंक डिल्लिबजार शाखाले दिएको चेक बाउन्सको फेक रिपोर्टका आधारमा महानगरीय प्रहरी परिसर ललितपुरले दाङ तुलसीपुर– स्थायी ठेगाना भएकी ललितपुरको नखिपोट बस्ने शिक्षा पेशामा आवद्ध भएकी कान्ति गिरी र उनका पति रुपेश श्रेष्ठलाई सोही आधारमा ललितपुर प्रहरीले केही साता अघि पक्राउ गर्‍यो   साउनमा प्रहरीले धरौटीमा रिहा हुनसाथ पुनः गिरी दम्पत्तीलाई पक्राउ गरेको थियो  बैंकिङ कसुरका लागि बैंकले तीन पटक चेक बाउन्स गर्न तीन साता लगाउँछ तर डिल्लिबजार शाखाले पीडकको दबाबमा आएर तीन दिनमा नै तीन पटक बाउन्स गरिदियो    र  असारमा चेक बाउन्सको रिपोर्ट बनाएपछि पीडकले गिरी दम्पत्तीलाई प्रहरीसम्म पुराए  उक्त खाता  असारमा नै बन्द गरिएको थियो  गिरीको एनआइसी एसीया बैंकको डिल्लिबजार शाखाको खाता नम्बर  को चेक पीडक दम्पत्ती राजेश र प्रिती अवालेले धम्की दिएर काट्न लगाएको पीडितले बताएका छन्  यस्तै धम्की दिएरै विभिन्न मितिका अन्य चेक पनि अवाले दम्पत्तीले काट्न लगाएको छ  ललितपुर परिसरमा यसअघिको छलफलका क्रममा पीडि

Word by word split down

In [63]:
for i,t in enumerate(X_data):
    word = X_data[i].split(" ")
    X_data[i] = " ".join(ele for ele in word if ele not in to_be_removed)

In [21]:
dataset.head()

गुनासो वर्ग  \
0  अर्थ सबन्धी   
1  अर्थ सबन्धी   
2  अर्थ सबन्धी   
3  अर्थ सबन्धी   
4  अर्थ सबन्धी   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 गुनासो  
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ओम शिव शक्ति बचत तथा ऋण सहकारी संस्थाले युवा स्वरोजगार कार्यक्रमबाट सहकारी मार्फत कार्यक्रम सञ्चालन गर्ने भनि करिब  व्यक्तिको फायल तयार गरी करिव  करोड रूपैया निकासी गरेतापनि सम्बन्धित व्यक्तिलाई रूपैया नदिएर यस सहकारी संस्थाको अध्यक्षले उक्त रकम आफूले जग्गा पलटिङको कार्यमा प्रयोग गरेका छन् कार्यक्रमको अनुगमनको लागि नेपाल सरकारका कर्मचारी आएपनि उहाँहरू बिरगञ्जको कुनै होटलमा बसि फर्किनु भएको छ  यस बारे छानविन गरी कारवाही गरिपाउँ  
1  एनआइसी एसीया बैंक डिल्लिबजार शाखाले दिएको चेक बाउन्सको फेक रिपोर्टका आधारमा महानगरीय प्रहरी परिसर ललितपुरले दाङ तुलसीपुर– स्थायी ठेगाना भएकी ललितपुरको नखिपोट बस्ने शिक्षा पेशामा आवद्ध भएकी कान्ति गिरी र उनका पति रुपेश श्रेष्ठलाई सोही आधारमा ललितपुर प्रहरीले केही साता अघि पक्राउ गर्‍यो   साउनमा प्रहरीले धरौटीमा रिहा हुनसाथ पुनः गिरी दम्पत्तीलाई पक्राउ गरेको थियो  बैंकिङ कसुरका लागि बैंकले तीन पटक चेक बाउन्स गर्न तीन साता लगाउँछ तर डिल्लिबजार शाखाले पीडकको दबाबमा आएर तीन दिनमा नै तीन पटक बाउन्स गरिदियो    र  असारमा चेक बाउन्सको रिपोर्ट बनाएपछि पीडकले गिरी दम्पत्तीलाई प्रहरीसम्म पुराए  उक्त खाता  असारमा नै बन्द गरिएको थियो  गिरीको एनआइसी एसीया बैंकको डिल्लिबजार शाखाको खाता नम्बर  को चेक पीडक दम्पत्ती राजेश र प्रिती अवालेले धम्की दिएर काट्न लगाएको पीडितले बताएका छन्  यस्तै धम्की दिएरै विभिन्न मितिका अन्य चेक पनि अवाले दम्पत्तीले काट्न लगाएको छ  ललितपुर परिसरमा यसअघिको छलफलका क्रममा पीडि

### Vectorizer

In [22]:
X1=dataset['गुनासो']
Y1=list(dataset['गुनासो वर्ग'])

In [23]:
from sklearn.model_selection import train_test_split

In [37]:
X_train,X_test,Y_train,Y_test=train_test_split(X1,Y1,test_size=0.30,random_state=0)

Term frequency count by TFIDF(Term Frequency Inverse Document Frequency) (Repeated word count for ML analysis)

In [38]:

from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
def tfidf_features(X_train, X_test):
    tfidf_vectorizer = TfidfVectorizer(stop_words=stopWords)
    X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
    X_test_tfidf = tfidf_vectorizer.transform(X_test)
    return X_train_tfidf,X_test_tfidf,tfidf_vectorizer.vocabulary_
X_train_tfidf,X_test_tfidf,vocabulary=tfidf_features(X_train,X_test)


C:\Users\Dell\AppData\Roaming\Python\Python310\site-packages\sklearn\feature_extraction\text.py:404: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['अक', 'अग', 'अझ', 'अन', 'अर', 'आजक', 'आत', 'आद', 'आफ', 'आय', 'ईक', 'उद', 'उनक', 'उनल', 'उह', 'एउट', 'एन', 'कत', 'कम', 'कस', 'कसर', 'कह', 'गत', 'गय', 'गर', 'चम', 'छन', 'जत', 'जबक', 'जस', 'जसक', 'जसब', 'जसम', 'जसल', 'जह', 'तत', 'तथ', 'तदन', 'तप', 'तवम', 'नज', 'नत', 'नभन', 'नय', 'पक', 'पछ', 'पन', 'पय', 'पर', 'पष', 'पह', 'बन', 'बर', 'भएक', 'भय', 'भव', 'मल', 'यत', 'यथ', 'यद', 'यप', 'यसक', 'यसपछ', 'यसब', 'यसर', 'यह', 'रण', 'रत', 'रमश', 'रह', 'लस', 'वर', 'सक', 'सट', 'सध', 'सपछ', 'सब', 'सम', 'सर', 'सह', 'हन', 'हर', 'हरण'] not in stop_words.
  warnings.warn(


In [40]:
#Convert Sparse to Dense
X_train_Vectorized_Dense = X_train_tfidf.todense()
X_test_Vectorized_Dense = X_test_tfidf.todense()

### ML ALGO

In [41]:
from sklearn.svm import LinearSVC
from sklearn.ensemble import ExtraTreesClassifier,GradientBoostingClassifier,RandomForestClassifier,AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression,RidgeClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

Function for accuracy and F1 for Dense

In [43]:
def ClassificationAlgorithm_dense(func, **kwargs):

  def innerFunction():
    model = func(**kwargs)
    model.fit(X_train_Vectorized_Dense, Y_train)

    Y_pred = model.predict(X_test_Vectorized_Dense)
    
    print("Confusion Matrix : \n",confusion_matrix(Y_test,Y_pred),"\n")
    print("Accuracy Score : ",accuracy_score(Y_test,Y_pred))
    print("F1 Score : ",f1_score(Y_test,Y_pred,average='weighted'))

  return innerFunction()

Function for accuracy and F1 for sparse

In [31]:
def ClassificationAlgorithm(func, **kwargs):

  def innerFunction():
    model = func(**kwargs)
    model.fit(X_train_tfidf,Y_train)
    
    Y_pred= model.predict(X_test_tfidf)
    
    print ("Confusion Matrix : \n", confusion_matrix(Y_test, Y_pred), "\n")
    print("Testing Accuracy is  :%s" %(model.score(X_test_tfidf, Y_test)))
    print ("F1 Score : " , f1_score(Y_test, Y_pred, average='weighted'))
    
  return innerFunction()

### SUPPORT VECTOR MACHINE (SVM)

In [32]:
from sklearn.svm import LinearSVC
ClassificationAlgorithm(LinearSVC)

Confusion Matrix : 
 [[124  15  16  65]
 [ 14  55   4  58]
 [ 14   7  91  53]
 [ 26   9   4 170]] 

Testing Accuracy is  :0.6068965517241379
F1 Score :  0.6052096456905262


In [33]:
from sklearn.svm import SVC
ClassificationAlgorithm(SVC,kernel='rbf')

Confusion Matrix : 
 [[128   0   6  86]
 [ 20  38   4  69]
 [ 21   1  81  62]
 [ 28   2   4 175]] 

Testing Accuracy is  :0.5820689655172414
F1 Score :  0.5758140352999088


In [34]:
from sklearn.svm import SVC
ClassificationAlgorithm(SVC,kernel='poly')

Confusion Matrix : 
 [[105   0   4 111]
 [ 19  17   2  93]
 [ 11   1  60  93]
 [ 18   0   1 190]] 

Testing Accuracy is  :0.5131034482758621
F1 Score :  0.48718238655241747



### Naive Bayes

In [ ]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, ComplementNB

In [35]:
#Convert Sparse to Dense
X_train_Vectorized_Dense = X_train_tfidf.todense()
X_test_Vectorized_Dense = X_test_tfidf.todense()

Gaussian Naive Bayes'

In [36]:
from sklearn.naive_bayes import GaussianNB
ClassificationAlgorithm_dense(GaussianNB)

C:\Users\Dell\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
C:\Users\Dell\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


Confusion Matrix : 
 [[ 65  20 108  27]
 [ 21  32  62  16]
 [ 18  11 125  11]
 [ 30  24  97  58]] 

Accuracy Score :  0.38620689655172413
F1 Score :  0.37080497438269344


Bernouli Naive Bayes'

In [ ]:
ClassificationAlgorithm_dense(BernoulliNB)

Multinomial Naive Bayes'

In [ ]:
ClassificationAlgorithm_dense(MultinomialNB)

Complement Naive Bayes'

In [ ]:
ClassificationAlgorithm_dense(ComplementNB)

### Multi lingual bert

In [39]:
from simpletransformers.classification import ClassificationModel

In [40]:
print(set(Y_train))

{'स्वास्थ्यसँग सम्बन्धी', 'शान्ति सुरक्षा सम्बन्धी', 'अर्थ सबन्धी', 'सूचना तथा संचार सम्बन्धी'}


In [41]:
from sklearn import preprocessing
labeler = preprocessing.LabelEncoder()

df3 = pd.DataFrame(X_train)
df3['label'] = labeler.fit_transform(Y_train)
print(df3.head())

                                                                                                                                                                                                                                                                                                गुनासो  \
610                                                                                                             बिज्ञापन निकालेर राजस्ब लिएको महीनौ बितीसकदा पनि     र राजस्ब लीएर अहीले सम्म कुनैपनि परीक्षा मिति निकालेको छैन \ राज्सब फ्रिता गरिपाउ या परिक्षा काे मिति पाउ भनि याे सानाे अनुराेध छ   
1458  दुवै  र  को नेटवर्क ले राम्रो काम गर्दैन    देखाउँछ तर कल लाग्दैन   धरी चेक हुँदैन       आउछ तर  र  राम्रो चल्दैन  नेट चलाउनु फरक फरक ठाउँ खोज्दै की बाटोतिर की खेत तिर जानुपर्छ  समस्या फोन गर्दा कसैलाई लाग्दैन नेटवर्क को समस्या धरै  हाम्रो एरिया मा  कृपया यसको समाधान गरिदिनु होला धन्यवाद   
2848                                                                                                      

In [40]:
model = ClassificationModel('bert', 'bert-base-multilingual-uncased', num_labels=4, use_cuda=False, args={
    'reprocess_input_data': True,
    'use_cached_eval_features': False,
    'overwrite_output_dir': True,
    'num_train_epochs': 3
})
model.train_model(df3)
print("trained model")

Some weights of the model checkpoint at bert-base-multilingual-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model 

  0%|          | 0/2173 [00:00<?, ?it/s]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The 

Epoch:   0%|          | 0/3 [00:00<?, ?it/s]

Running Epoch 0 of 3:   0%|          | 0/272 [00:00<?, ?it/s]

Running Epoch 1 of 3:   0%|          | 0/272 [00:00<?, ?it/s]

Running Epoch 2 of 3:   0%|          | 0/272 [00:00<?, ?it/s]

trained model


In [41]:
eval_frame = pd.DataFrame(X_test)
eval_frame['label'] = labeler.fit_transform(Y_test)
print(eval_frame.head())

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   गुनासो  \
1946                                                                                                                                                                                                                                       

In [42]:
print(len(eval_frame))

725


In [43]:
result, model_outputs, wrong_predictions = model.eval_model(eval_frame)
bads = {}
for pred in wrong_predictions:
    if pred.label in bads:
        bads[pred.label] += 1
    else:
        bads[pred.label] = 1
print("wrong predictions (by input I think?):")
print(bads)

/Users/badalgami/opt/anaconda3/lib/python3.9/site-packages/simpletransformers/classification/classification_model.py:1442: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  warnings.warn(


  0%|          | 0/725 [00:00<?, ?it/s]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


Running Evaluation:   0%|          | 0/91 [00:00<?, ?it/s]

wrong predictions (by input I think?):
{0: 107, 1: 64, 3: 50, 2: 81}


In [46]:
(1-(107+64+50+81)/725)*100

58.34482758620689