# GRIEVANCE SEGRIGATION 

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_colwidth',None)   
import collections
from collections import Counter

In [2]:
dataset = pd.read_excel("4_label.xlsx")

In [3]:
dataset.head()

गुनासो वर्ग  \
0  अर्थ सबन्धी   
1  अर्थ सबन्धी   
2  अर्थ सबन्धी   
3  अर्थ सबन्धी   
4  अर्थ सबन्धी   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      गुनासो  
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ओम शिव शक्ति बचत तथा ऋण सहकारी संस्थाले युवा स्वरोजगार कार्यक्रमबाट सहकारी मार्फत कार्यक्रम सञ्चालन गर्ने भनि करिब ३०-४० व्यक्तिको फायल तयार गरी करिव २ करोड रूपैया निकासी गरेतापनि सम्बन्धित व्यक्तिलाई रूपैया नदिएर यस सहकारी संस्थाको अध्यक्षले उक्त रकम आफूले जग्गा पलटिङको कार्यमा प्रयोग गरेका छन्। कार्यक्रमको अनुगमनको लागि नेपाल सरकारका कर्मचारी आएपनि उहाँहरू बिरगञ्जको कुनै होटलमा बसि फर्किनु भएको छ । यस बारे छानविन गरी कारवाही गरिपाउँ ।  
1  एनआइसी एसीया बैंक डिल्लिबजार शाखाले दिएको चेक बाउन्सको फेक रिपोर्टका आधारमा महानगरीय प्रहरी परिसर ललितपुरले दाङ तुलसीपुर–५ स्थायी ठेगाना भएकी ललितपुरको नखिपोट बस्ने शिक्षा पेशामा आवद्ध भएकी कान्ति गिरी र उनका पति रुपेश श्रेष्ठलाई सोही आधारमा ललितपुर प्रहरीले केही साता अघि पक्राउ गर्‍यो । १ साउनमा प्रहरीले धरौटीमा रिहा हुनसाथ पुनः गिरी दम्पत्तीलाई पक्राउ गरेको थियो । बैंकिङ कसुरका लागि बैंकले तीन पटक चेक बाउन्स गर्न तीन साता लगाउँछ तर डिल्लिबजार शाखाले पीडकको दबाबमा आएर तीन दिनमा नै तीन पटक बाउन्स गरिदियो । १७, १८ र १९ असारमा चेक बाउन्सको रिपोर्ट बनाएपछि पीडकले गिरी दम्पत्तीलाई प्रहरीसम्म पुराए । उक्त खाता १० असारमा नै बन्द गरिएको थियो । गिरीको एनआइसी एसीया बैंकको डिल्लिबजार शाखाको खाता नम्बर २९५६३५१८२१५२४००१ को चेक पीडक दम्पत्ती राजेश र प्रिती अवालेले धम्की दिएर काट्न लगाएको पीड

In [4]:
X=dataset['गुनासो']
Y=list(dataset['गुनासो वर्ग'])

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2898 entries, 0 to 2897
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   गुनासो वर्ग  2898 non-null   object
 1   गुनासो       2898 non-null   object
dtypes: object(2)
memory usage: 45.4+ KB


### Remove stopwords

In [6]:
import nltk
from nltk.corpus import stopwords

In [7]:
stopWords = set(nltk.corpus.stopwords.words('nepali'))

In [8]:
stopWords=set(stopwords.words('nepali'))
X_data=[]
for i in X:
    गुनासो=' '.join([word for word in i.split() if word not in stopWords])
    X_data.append(गुनासो.strip())

In [9]:
Stopwords = set(nltk.corpus.stopwords.words('english'))

In [10]:
Stopwords=set(stopwords.words('english'))
X_data=[]
for i in X:
    गुनासो=' '.join([word for word in i.split() if word not in Stopwords])
    X_data.append(गुनासो.strip())

In [11]:
#removing all unnecessary expression
import re
def processText(गुनासो):
    गुनासो = गुनासो.lower()
    गुनासो = re.sub('[s]+', ' ',गुनासो)
    गुनासो = re.sub(r'#([^s]+)', r'1', गुनासो)
    गुनासो = re.sub(r'[.!:?"\।/-|,]', r'', गुनासो)
    गुनासो = गुनासो.strip('"')
    return गुनासो

In [12]:
for i in range(len(dataset)):
    dataset['गुनासो'][i] = processText(dataset['गुनासो'][i])

In [13]:
dataset.tail()

गुनासो वर्ग  \
2893  शान्ति सुरक्षा सम्बन्धी   
2894  शान्ति सुरक्षा सम्बन्धी   
2895  शान्ति सुरक्षा सम्बन्धी   
2896  शान्ति सुरक्षा सम्बन्धी   
2897  शान्ति सुरक्षा सम्बन्धी   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            गुनासो  
2893  विषय  मेरो जिउ ज्यान धनमा शान्ति सुरक्षा गरी पाउँ  जिल्ला रौतहट गाविस सोनरनिया वाडा न२ भई हाल मौलापर ना पा वाड़ा नं८ मा बस्ने गरि हाल जिल्ला बारा कलैया उ म न पा वड़ा नं१ टोल मोतीबागमा बस्ने मातृका प्रसाद यादवको छोरी जयगोविन्द राय यादवको बुहारी दया शंकर प्रसाद यादवको श्रीमती वर्ष ३८ की सन्ध्या कमारी यादव  ‌ विरुद्ध जिल्ला‌ बारा आदर्श कोतवाल गापा वाडा नं ३ गाउँ भटिनिया भई हाल कलैया उमन पा वाडा न ५ टोल घुसुकपुरमा बस्ने चुआ राय यादवको नाती रामप्रित राय यादवको छोरा अ वर्ष ४९ को अनिल कुमार प्रियादर्शी निज विपक्षी समेत मली सोझा साझा सिधा मानिसहरूलाई झुक्याई आफ्नो प्रलोभनमा पारी कसैलाई रुपैंयाँको आवश्यकता पर्दा निजले रुपैयाँ दिई ५ गुनाको कागज गराउने कसैसंग सो रूपैयाँ बापतको ४-५ गुनाको चेक कटाउन लगाई सो को मिटर ब्याज नोटि सो को ५ गुना ब्याज लगाई एउटा उगी किसिमको निजको चाल चलन व्यवहार रहेका हुंदा निजले बिगत मिति २०७६ सालमा निज मेरो पति दयाशंकर प्रसाद यादवले आफ्नो घर व्यवहार चलाउनको लागि निज विपक्षी संग रु १४००००० चौदह लाख रुपैया लिएकोमा सो रुपैया कर्जाको २०७६ सालमा नै निज मेरो पति दयाशंकर प्रसाद यादवले पटक पटक गरि मिटर व्याज लगाई रु २६०००००- छविस लाख रुपैया निज विपक्षी लिई बुझी लिएको रुपैया अब बाँकी लिन छैन मेरो पतिले बलैक चेक आफनो फिर्ता माग्दा आज भोली भनी पख

### Vectorizer

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,Y_train,Y_test=train_test_split(X_data,Y,test_size=0.25,random_state=0)

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [17]:
def tfidf_features(X_train, X_test):
    tfidf_vectorizer = TfidfVectorizer(max_features=5000)
    X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
    X_test_tfidf = tfidf_vectorizer.transform(X_test)
    return X_train_tfidf,X_test_tfidf,tfidf_vectorizer.vocabulary_
X_train_tfidf,X_test_tfidf,vocabulary=tfidf_features(X_train,X_test)

### ML ALGO

In [18]:
from sklearn.svm import LinearSVC
from sklearn.ensemble import ExtraTreesClassifier,GradientBoostingClassifier,RandomForestClassifier,AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression,RidgeClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

In [20]:
from sklearn.metrics import classification_report

In [21]:
def ClassificationAlgorithm_dense(func, **kwargs):

  def innerFunction():
    model = func(**kwargs)
    model.fit(X_train_Vectorized_Dense, Y_train)

    Y_pred = model.predict(X_test_Vectorized_Dense)
    
    print("Confusion Matrix : \n",classification_report(Y_test,Y_pred),"\n")
    print("Confusion Matrix : \n",confusion_matrix(Y_test,Y_pred),"\n")
    print("Accuracy Score : ",accuracy_score(Y_test,Y_pred))
    print("F1 Score : ",f1_score(Y_test,Y_pred,average='weighted'))

  return innerFunction()

In [22]:
def ClassificationAlgorithm(func, **kwargs):

  def innerFunction():
    model = func(**kwargs)
    model.fit(X_train_tfidf,Y_train)
    
    Y_pred= model.predict(X_test_tfidf)
    
    print ("Confusion Matrix : \n", confusion_matrix(Y_test, Y_pred), "\n")
    print("Testing Accuracy is  :%s" %(model.score(X_test_tfidf, Y_test)))
    print ("F1 Score : " , f1_score(Y_test, Y_pred, average='weighted'))
    
  return innerFunction()

### SUPPORT VECTOR MACHINE (SVM)

In [23]:
from sklearn.svm import LinearSVC
ClassificationAlgorithm(LinearSVC)

Confusion Matrix : 
 [[166  18  11  25]
 [ 12  93   4  22]
 [ 17   4 128  16]
 [ 27   9   4 169]] 

Testing Accuracy is  :0.766896551724138
F1 Score :  0.7674101605275179


In [24]:
from sklearn.svm import SVC
ClassificationAlgorithm(SVC,kernel='rbf')

Confusion Matrix : 
 [[184   2   6  28]
 [ 22  76   3  30]
 [ 23   2 118  22]
 [ 28   2   3 176]] 

Testing Accuracy is  :0.7641379310344828
F1 Score :  0.7633403918284943


In [25]:
from sklearn.svm import SVC
ClassificationAlgorithm(SVC,kernel='poly')

Confusion Matrix : 
 [[141   0   1  78]
 [ 28  37   1  65]
 [ 13   1  72  79]
 [ 21   0   1 187]] 

Testing Accuracy is  :0.6027586206896551
F1 Score :  0.592427329737211


### Naive Bayes

In [26]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, ComplementNB

In [27]:
#Convert Sparse to Dense
X_train_Vectorized_Dense = X_train_tfidf.todense()
X_test_Vectorized_Dense = X_test_tfidf.todense()

In [28]:
from sklearn.naive_bayes import GaussianNB
ClassificationAlgorithm_dense(GaussianNB)

C:\Users\Dell\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
C:\Users\Dell\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


Confusion Matrix : 
                           precision    recall  f1-score   support

             अर्थ सबन्धी       0.61      0.47      0.53       220
 शान्ति सुरक्षा सम्बन्धी       0.51      0.53      0.52       131
सूचना तथा संचार सम्बन्धी       0.50      0.68      0.58       165
   स्वास्थ्यसँग सम्बन्धी       0.58      0.53      0.55       209

                accuracy                           0.55       725
               macro avg       0.55      0.55      0.55       725
            weighted avg       0.56      0.55      0.55       725
 

Confusion Matrix : 
 [[104  27  51  38]
 [ 18  70  21  22]
 [ 18  13 112  22]
 [ 31  28  39 111]] 

Accuracy Score :  0.5475862068965517
F1 Score :  0.5460514884828628


In [29]:
ClassificationAlgorithm_dense(BernoulliNB)

C:\Users\Dell\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
C:\Users\Dell\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


Confusion Matrix : 
                           precision    recall  f1-score   support

             अर्थ सबन्धी       0.78      0.54      0.64       220
 शान्ति सुरक्षा सम्बन्धी       0.93      0.44      0.59       131
सूचना तथा संचार सम्बन्धी       0.68      0.82      0.74       165
   स्वास्थ्यसँग सम्बन्धी       0.59      0.88      0.70       209

                accuracy                           0.68       725
               macro avg       0.74      0.67      0.67       725
            weighted avg       0.73      0.68      0.67       725
 

Confusion Matrix : 
 [[119   1  35  65]
 [ 14  57  16  44]
 [  9   1 135  20]
 [ 11   2  13 183]] 

Accuracy Score :  0.6813793103448276
F1 Score :  0.6722319891471374


In [30]:
ClassificationAlgorithm_dense(MultinomialNB)

Confusion Matrix : 
                           precision    recall  f1-score   support

             अर्थ सबन्धी       0.69      0.76      0.72       220
 शान्ति सुरक्षा सम्बन्धी       0.86      0.34      0.48       131
सूचना तथा संचार सम्बन्धी       0.93      0.70      0.80       165
   स्वास्थ्यसँग सम्बन्धी       0.61      0.89      0.72       209

                accuracy                           0.71       725
               macro avg       0.77      0.67      0.68       725
            weighted avg       0.75      0.71      0.70       725
 

Confusion Matrix : 
 [[167   3   6  44]
 [ 38  44   1  48]
 [ 21   1 115  28]
 [ 17   3   2 187]] 

Accuracy Score :  0.7075862068965517
F1 Score :  0.696336742109145


C:\Users\Dell\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
C:\Users\Dell\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


In [31]:
ClassificationAlgorithm_dense(ComplementNB)

Confusion Matrix : 
                           precision    recall  f1-score   support

             अर्थ सबन्धी       0.76      0.75      0.76       220
 शान्ति सुरक्षा सम्बन्धी       0.78      0.58      0.66       131
सूचना तथा संचार सम्बन्धी       0.82      0.83      0.82       165
   स्वास्थ्यसँग सम्बन्धी       0.71      0.81      0.76       209

                accuracy                           0.76       725
               macro avg       0.76      0.74      0.75       725
            weighted avg       0.76      0.76      0.76       725
 

Confusion Matrix : 
 [[166   9  15  30]
 [ 20  76   8  27]
 [ 11   3 137  14]
 [ 21  10   8 170]] 

Accuracy Score :  0.7572413793103449
F1 Score :  0.7550163211171848


C:\Users\Dell\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
C:\Users\Dell\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(
